routes/web.php
<?php

use App\Http\Controllers\ProfileController;
use App\Http\Controllers\Admin\CustomerController;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Route::get('/dashboard', function () {
    return view('dashboard');
})->middleware(['auth', 'verified'])->name('dashboard');

Route::middleware('auth')->group(function () {
    Route::get('/profile', [ProfileController::class, 'edit'])->name('profile.edit');
    Route::patch('/profile', [ProfileController::class, 'update'])->name('profile.update');
    Route::delete('/profile', [ProfileController::class, 'destroy'])->name('profile.destroy');
    Route::resource('/customers', CustomerController::class);
});

require __DIR__.'/auth.php';

app/Models/Customer.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Customer extends Model
{
    use HasFactory;
    protected $fillable = [
        'first_name',
        'last_name',
        'email',
        'user_name',
        'salary',
        'status',
    ];
}

app/Http/Controllers/API/CustomerController.php
<?php

namespace App\Http\Controllers\API;

use App\Events\CustomerCreated;
use App\Http\Controllers\Controller;
use App\Http\Requests\API\CreateCustomerRequest;
use App\Http\Requests\API\UpdateCustomerRequest;
use App\Http\Resources\API\CustomerResource;
use App\Models\Customer;
use Illuminate\Database\Eloquent\Model;

class CustomerController extends Controller
{
    private Model $model;
    public function __construct(Customer $model)
    {
        $this->model = $model;
    }
    public function index(): \Illuminate\Http\JsonResponse
    {
        return response()->json([
            'status' => true,
            'data' => CustomerResource::collection($this->model->all())
        ]);
    }

    public function store(CreateCustomerRequest $request): \Illuminate\Http\JsonResponse
    {
        $customer = $this->model->create($request->validated());
        event(new CustomerCreated($customer));

        return response()->json([
            'status' => true,
            'message' => "customer-created",
            'data' => new CustomerResource($customer)
        ]);
    }

    public function show($id): \Illuminate\Http\JsonResponse
    {
        return response()->json([
            'status' => true,
            'message' => "customer-created",
            'data' => new CustomerResource($this->model->find($id))
        ]);
    }

    public function update(UpdateCustomerRequest $request, $id): \Illuminate\Http\JsonResponse
    {
        Customer::where('id', $id)->update($request->validated());
        return response()->json([
            'status' => true,
            'message' => "customer-update"
        ]);
    }

    public function destroy($id): \Illuminate\Http\JsonResponse
    {
        $customer = Customer::find($id);
        $customer->delete($id);

        return response()->json([
            'status' => true,
            'message' => "customer-deleted"
        ]);
    }
}

app/Http/Controllers/Admin/CustomerController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Events\CustomerCreated;
use App\Http\Controllers\Controller;
use App\Http\Requests\Admin\CreateCustomerRequest;
use App\Http\Requests\Admin\UpdateCustomerRequest;
use App\Models\Customer;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Http\RedirectResponse;
use Illuminate\Http\Request;
use Illuminate\Http\Response;
use Illuminate\View\View;
use Illuminate\Support\Facades\Redirect;

class CustomerController extends Controller
{

    private Model $model;
    public function __construct(Customer $model)
    {
        $this->model = $model;
    }

    /**
     * Display a listing of the resource.
     *
     * @return View
     */
    public function index(): View
    {
        return view('customer.index', [
            'customers' => $this->model->all(),
        ]);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return View
     */
    public function create(): View
    {
        return view('customer.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param CreateCustomerRequest $request
     * @return RedirectResponse
     */
    public function store(CreateCustomerRequest $request): RedirectResponse
    {
        $customer = $this->model->create($request->validated());
        event(new CustomerCreated($customer));

        return Redirect::route('customers.index')->with('status', 'customer-created');

    }

    /**
     * Display the specified resource.
     *
     * @param int $id
     * @return View
     */
    public function show(int $id): View
    {
        return view('customer.show', [
            'customer' => $this->model->find($id),
        ]);
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param int $id
     * @return View
     */
    public function edit(int $id): View
    {
        return view('customer.edit', [
            'customer' => Customer::find($id)
        ]);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param UpdateCustomerRequest $request
     * @param int $id
     * @return Response
     */
    public function update(UpdateCustomerRequest $request, int $id): RedirectResponse
    {
        Customer::where('id', $id)->update($request->validated());
        return Redirect::route('customers.index')->with('status', 'customer-updated');

    }

    /**
     * Remove the specified resource from storage.
     *
     * @param int $id
     * @return Response
     */
    public function destroy(int $id): Response
    {
        $customer = Customer::find($id);
        $customer->delete($id);

        return Redirect::route('customers.index')->with('status', 'customer-deleted');
    }
}

app/View/Components/AppLayout.php
<?php

namespace App\View\Components;

use Illuminate\View\Component;
use Illuminate\View\View;

class AppLayout extends Component
{
    /**
     * Get the view / contents that represents the component.
     */
    public function render(): View
    {
        return view('layouts.app');
    }
}

resources/views/customer/create.blade.php
<x-app-layout>
    @if($errors->any())
        {{ implode('', $errors->all(':message')) }}
    @endif
        <x-slot name="header">
            <h2 class="font-semibold text-xl text-gray-800 leading-tight">
                {{ __('Create New Customer') }}
            </h2>
        </x-slot>
        <div class="py-12">
            <div class="max-w-7xl mx-auto sm:px-6 lg:px-8 space-y-6">
                <form method="POST" action="{{ route('customers.store') }}" class="mt-6 space-y-6">
                @csrf

                <!-- First Name -->
                <div>
                    <x-input-label for="name" :value="__('First Name')" />
                    <x-text-input id="name" class="block mt-1 w-full" type="text" name="first_name" :value="old('first_name')" required autofocus autocomplete="first_name" />
                    <x-input-error :messages="$errors->get('first_name')" class="mt-2" />
                </div>
                <!-- Last Name -->
                <div>
                    <x-input-label for="name" :value="__('Last Name')" />
                    <x-text-input id="name" class="block mt-1 w-full" type="text" name="last_name" :value="old('last_name')" required autofocus autocomplete="last_name" />
                    <x-input-error :messages="$errors->get('last_name')" class="mt-2" />
                </div>

                <!-- Email Address -->
                <div class="mt-4">
                    <x-input-label for="email" :value="__('Email')" />
                    <x-text-input id="email" class="block mt-1 w-full" type="email" name="email" :value="old('email')" required autocomplete="username" />
                    <x-input-error :messages="$errors->get('email')" class="mt-2" />
                </div>

                <!-- User Name -->
                <div>
                    <x-input-label for="user_name" :value="__('User Name')" />
                    <x-text-input id="user_name" class="block mt-1 w-full" type="text" name="user_name" :value="old('user_name')" required autofocus autocomplete="last_name" />
                    <x-input-error :messages="$errors->get('user_name')" class="mt-2" />
                </div>

                <!-- Salary -->
                <div>
                    <x-input-label for="salary" :value="__('Salary')" />
                    <x-text-input id="salary" class="block mt-1 w-full" type="number" name="salary" :value="old('salary')" required autofocus autocomplete="salary" />
                    <x-input-error :messages="$errors->get('salary')" class="mt-2" />
                </div>
                <!-- Status -->
                <div>
                    <x-input-label for="status" :value="__('Status')" />
                    <x-text-input id="status" class="block mt-1" type="checkbox" name="status"   autofocus autocomplete="status" />
                    <x-input-error :messages="$errors->get('status')" class="mt-2" />
                </div>

                <div class="flex items-center justify-end mt-4">
                    <x-primary-button class="ml-4">
                        {{ __('Save') }}
                    </x-primary-button>
                </div>
            </form>
            </div>
        </div>
</x-app-layout>

resources/views/customer/edit.blade.php
<x-app-layout>
    @if($errors->any())
        {{ implode('', $errors->all(':message')) }}
    @endif
    <x-slot name="header">
        <h2 class="font-semibold text-xl text-gray-800 leading-tight">
            {{ __('Edit') }}
        </h2>
    </x-slot>
    <div class="py-12">
        <div class="max-w-7xl mx-auto sm:px-6 lg:px-8 space-y-6">
            <form method="POST" action="{{ route('customers.update', ['customer'=>1]) }}" class="mt-6 space-y-6">
                @csrf
                @method('patch')

                <!-- First Name -->
                <div>
                    <x-input-label for="name" :value="__('First Name')" />
                    <x-text-input id="name" class="block mt-1 w-full" type="text" name="first_name" value="{{$customer->first_name}}" required autofocus autocomplete="first_name" />
                    <x-input-error :messages="$errors->get('first_name')" class="mt-2" />
                </div>
                <!-- Last Name -->
                <div>
                    <x-input-label for="name" :value="__('Last Name')" />
                    <x-text-input id="name" class="block mt-1 w-full" type="text" name="last_name" value="{{$customer->last_name}}" required autofocus autocomplete="last_name" />
                    <x-input-error :messages="$errors->get('last_name')" class="mt-2" />
                </div>

                <!-- Email Address -->
                <div class="mt-4">
                    <x-input-label for="email" :value="__('Email')" />
                    <x-text-input id="email" class="block mt-1 w-full" type="email" name="email" value="{{$customer->email}}" required autocomplete="username" />
                    <x-input-error :messages="$errors->get('email')" class="mt-2" />
                </div>

                <!-- User Name -->
                <div>
                    <x-input-label for="user_name" :value="__('User Name')" />
                    <x-text-input id="user_name" class="block mt-1 w-full" type="text" name="user_name" value="{{$customer->user_name}}" required autofocus autocomplete="last_name" />
                    <x-input-error :messages="$errors->get('user_name')" class="mt-2" />
                </div>

                <!-- Salary -->
                <div>
                    <x-input-label for="salary" :value="__('Salary')" />
                    <x-text-input id="salary" class="block mt-1 w-full" type="number" name="salary" value="{{$customer->salary}}" required autofocus autocomplete="salary" />
                    <x-input-error :messages="$errors->get('salary')" class="mt-2" />
                </div>
                <!-- Status -->
                <div>
                    <x-input-label for="status" :value="__('Status')" />
                    <x-text-input id="status" class="block mt-1" type="checkbox" name="status" required autofocus autocomplete="status" />
                    <x-input-error :messages="$errors->get('status')" class="mt-2" />
                </div>

                <div class="flex items-center justify-end mt-4">
                    <x-primary-button class="ml-4">
                        {{ __('Save') }}
                    </x-primary-button>
                </div>
            </form>
        </div>
    </div>
</x-app-layout>

resources/views/customer/index.blade.php
<x-app-layout>
    @if($errors->any())
        {{ implode('', $errors->all(':message')) }}
    @endif
    <x-slot name="header">
        <h2 class="font-semibold text-xl text-gray-800 leading-tight">
            {{ __('Create New Customer') }}
        </h2>
    </x-slot>
    <div class="py-12">
        <div class="max-w-7xl mx-auto sm:px-6 lg:px-12 space-y-6">
            <div >
                <table class="table table-striped ">
                    <thead>
                    <tr>
                        <th class="bg-gray-100">ID</th>
                        <th class="bg-gray-100">First Name</th>
                        <th class="bg-gray-100">Last Name</th>
                        <th class="bg-gray-100">Username</th>
                        <th>Email</th>
                        <th colspan="3">Actions</th>
                    </tr>
                    </thead>
                    <tbody>
                    @foreach($customers as $key => $value)
                        <tr>
                            <td>{{ $value->id }}</td>
                            <td>{{ $value->first_name }}</td>
                            <td>{{ $value->last_name }}</td>
                            <td>{{ $value->user_name }}</td>
                            <td>
                                <a href="mailto:{{ $value->email }}" title="Send email to {{ $value->email }}">
                                    {{ $value->email }}
                                </a>
                            </td>
                            <td>
                                {!! Form::open(array('url' => 'customers/' . $value->id, 'class' => 'pull-right')) !!}
                                {!! Form::hidden('_method', 'DELETE') !!}
                                {!! Form::button('<i class="fa fa-trash-o fa-fw" aria-hidden="true"></i> Delete', array('class' => 'btn btn-danger btn-block btn-flat','type' => 'button', 'data-toggle' => 'modal', 'data-target' => '#confirmDelete', 'data-title' => 'Delete User', 'data-message' => 'Are you sure you want to delete this user ?')) !!}
                                {!! Form::close() !!}
                            </td>
                            <td>
                                <a class="btn btn-small btn-success btn-block btn-flat"
                                   href="{{ URL::to('customers/' . $value->id) }}">Show</a>
                            </td>
                            <td>
                                <a class="btn btn-small btn-info btn-block btn-flat"
                                   href="{{ URL::to('customers/' . $value->id . '/edit') }}">Edit</a>
                            </td>
                        </tr>
                    @endforeach
                    </tbody>
                </table>
            </div>


        </div>
    </div>
</x-app-layout>

resources/views/customer/show.blade.php
<x-app-layout>
    @if($errors->any())
        {{ implode('', $errors->all(':message')) }}
    @endif
    <x-slot name="header">
        <h2 class="font-semibold text-xl text-gray-800 leading-tight">
            {{ __('Edit') }}
        </h2>
    </x-slot>
    <div class="py-12">
        <div class="max-w-7xl mx-auto sm:px-6 lg:px-8 space-y-6">
                <!-- First Name -->
                <div>
                    <x-input-label for="name" :value="__('First Name')" />
                    <x-text-input id="name" class="block mt-1 w-full" type="text" name="first_name" value="{{$customer->first_name}}" disabled />
                </div>
                <!-- Last Name -->
                <div>
                    <x-input-label for="name" :value="__('Last Name')" />
                    <x-text-input id="name" class="block mt-1 w-full" type="text" name="last_name"  value="{{$customer->last_name}}" disabled />
                </div>

                <!-- Email Address -->
                <div class="mt-4">
                    <x-input-label for="email" :value="__('Email')" />
                    <x-text-input id="email" class="block mt-1 w-full" type="email" name="email" value="{{$customer->email}}" disabled />
                    <x-input-error :messages="$errors->get('email')" class="mt-2" />
                </div>

                <!-- User Name -->
                <div>
                    <x-input-label for="user_name" :value="__('User Name')" />
                    <x-text-input id="user_name" class="block mt-1 w-full" type="text" name="user_name" value="{{$customer->user_name}}" disabled />
                </div>

                <!-- Salary -->
                <div>
                    <x-input-label for="salary" :value="__('Salary')" />
                    <x-text-input id="salary" class="block mt-1 w-full" type="number" name="salary" value="{{$customer->salary}}" disabled />
                </div>
                <!-- Status -->
                <div>
                    <x-input-label for="status" :value="__('Status')" />
                    <x-text-input id="status" class="block mt-1" type="checkbox" name="status" @checked($customer->status) disabled />
                </div>

        </div>
    </div>
</x-app-layout>